Update list.js
HisteriaMC/Histbot pull request #12
Opened 2024-01-23 10:01 UTC by SwouitAzia

Filtre la liste de joueurs connectés

2024-01-23 11:52 UTC, dadodasyra requested changes

2024-01-23 11:52 UTC, dadodasyra commented on commands/informations/list.js
> +        staffnbr = 0
Tu redéfini la variable dans la boucle

2024-01-23 11:52 UTC, dadodasyra commented on commands/informations/list.js
> +        if (stafflist.includes(player)) {
Condition inverse non ?

2024-01-23 11:52 UTC, dadodasyra commented on commands/informations/list.js
> +            let trueonlineplayers = response.onlinePlayers - getTrueOnlinePlayers(response.players, stafflist)
Reponse - la vraie ? Soit ta fonction est mal Nommé soit tu t'es trompé

2024-01-23 18:25 UTC, SwouitAzia commented on commands/informations/list.js
> +            let trueonlineplayers = response.onlinePlayers - getTrueOnlinePlayers(response.players, stafflist)
effectivement ce n'est pas clair je vais changer ça, enfaite je veux soustraire au nombre réel de joueurs connectés le nombre de staffs co.
ça serait plutôt getStaffOnlinePlayers

2024-01-23 18:26 UTC, SwouitAzia commented on commands/informations/list.js
> +        staffnbr = 0
ptn la boulette..

2024-01-23 18:27 UTC, SwouitAzia commented on commands/informations/list.js
> +        if (stafflist.includes(player)) {
non, j'augmente le nombre de staff de 1 SI player est contenu dans stafflist

2024-01-23 23:10 UTC, SwouitAzia commented
Avant de changer je dois encore faire une modif à cause des pseudos contenant des espaces.

2024-01-23 23:24 UTC, dadodasyra requested changes

2024-01-23 23:24 UTC, dadodasyra commented on commands/informations/list.js
> +function getStaffOnlinePlayers(players, stafflist) // Sert à avoir le nombre de staffs connectés
Tjr pas. Ca revient un peu au meme que dire getPlayersOnlinePlayers là

2024-01-23 23:24 UTC, dadodasyra commented on commands/informations/list.js
> +    "dadodasyra",
Je veux pas être dedans. Pareil ailfe modere pas donc on s'en fou

2024-01-24 08:02 UTC, dadodasyra commented on commands/informations/list.js
> +function getStaffOnlinePlayers(players, stafflist) // Sert à avoir le nombre de staffs connectés
```suggestion
function getOnlineStaffCount(players, stafflist) // Sert à avoir le nombre de staffs connectés
```

2024-01-24 08:05 UTC, dadodasyra requested changes

2024-01-24 08:05 UTC, dadodasyra commented on commands/informations/list.js
> +    staffnbr = 0
```suggestion
    staffnbr = 0
```
```suggestion
    let staffCount = 0
```

2024-01-24 08:05 UTC, dadodasyra commented on commands/informations/list.js
> +            staffnbr += 1
```suggestion
            staffCount += 1
```

2024-01-24 08:05 UTC, dadodasyra commented on commands/informations/list.js
> +    return staffnbr;
```suggestion
    return staffCount;
```

2024-01-25 17:10 UTC, dadodasyra requested changes

2024-01-25 17:10 UTC, dadodasyra commented on commands/informations/list.js
> +]
pourquoi c'est au milieu du fichier au milieu de nul part?

2024-01-25 17:10 UTC, dadodasyra commented on commands/informations/list.js
> +            let onlineplayerws = response.onlinePlayers - getStaffOnlinePlayers(response.players, stafflist) // online player without staff
```suggestion
            let onlineplayers = response.onlinePlayers - getStaffOnlinePlayers(response.players, stafflist) // online player without staff
```

2024-01-25 17:10 UTC, dadodasyra commented on commands/informations/list.js
> +        // Nombre de staff(s) connecté(s)
ce commentaire n'a rien à faire là

2024-01-25 17:10 UTC, dadodasyra commented on commands/informations/list.js
> +function getOnlineStaffCount(players, stafflist) // Sert à avoir le nombre de staffs connectés
toute la fonction remplacable par 
const onlineStaffCount = players.filter(value => stafflist.includes(value)).size;

2024-05-31 16:13 UTC, dadodasyra requested changes
Nothing to take from this code.
Comments ignored since months and the code wouldn't even work.
This should btw be got from the database

2024-05-31 16:13 UTC, dadodasyra commented on commands/informations/list.js
> +onlineStaffCount = players.filter(value => stafflist.includes(value)).size;
nan mais tu te fous de moi là, c'est une global, playersd n'existe pas ? tu executes ça de manière random ? ça compile meme pas là

2024-05-31 16:13 UTC, dadodasyra commented on commands/informations/list.js
> +stafflist = [
au début

2024-05-31 16:13 UTC, dadodasyra commented on commands/informations/list.js
> +onlineStaffCount = players.filter(value => stafflist.includes(value)).size;
la variable players n'existe pas ici, on est dans un contexte global, meme pas dans une fonction

2024-05-31 16:13 UTC, dadodasyra commented on commands/informations/list.js
> +stafflist = [
liste hardcodé à mettre au début du fichier

2024-05-31 16:13 UTC, dadodasyra commented
You may reopen a PR with a cleaner solution but this one lived enough.

2024-05-31 16:13 UTC, closed without merging